[package]
name = "influx"
version = "0.1.0"
authors = ["Grigoriy Baranov <baranov@w3m.co>"]
license = 'MIT'
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
