[package]
name = "influx"
description = "influx"
version = "0.1.5"
authors = ["Grigoriy Baranov <baranov@w3m.co>"]
license = "MIT"
edition = "2018"

exclude = [
    ".github",
    ".gitignore",
    "README.md"
]

[dependencies]
wdg-uri = "0.3.1"
string-repr = "1.0.1"
serde_json = "1.0.48"
