[package]
name = "influx"
description = "influx"
version = "0.1.1"
authors = ["Grigoriy Baranov <baranov@w3m.co>"]
license = "MIT"
edition = "2018"

exclude = [
    ".github",
    ".gitignore",
    "src/main.rs",
    "README.md"
]

[dependencies]
wdg-uri = "0.1.9"
